version: '3.9'

services:
  mysql-admin-management-db:
    image: mysql:latest
    container_name: container_mysql-admin-management-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin-management-db
      MYSQL_USER: diallo
      MYSQL_PASSWORD: passer
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  phpmyadmin-admin-db:
    container_name: container_phpmyadmin-adminmgntdb
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8085:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-admin-management-db
      PMA_USER: diallo
      PMA_PASSWORD: passer
    depends_on:
      - mysql-admin-management-db
    restart: unless-stopped

  # postgres service
  postgres-service:
    image: postgres
    container_name: postgres-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: k1234
    ports:
      - '5432:5432'
    expose:
      - '5432'
  # pgadmin interface web pour l'administration de postgresql
  pgadmin4-service:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: diallo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # keycloak
  keycloak-service:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-service:5432/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: k1234
      KEYCLOAK_ADMIN: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_ADMIN_PASSWORD: passer
    command:
      - start-dev
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - postgres-service

volumes:
  pgadmin_data:
  postgres_data:
  mysql_data:
    driver: local