version: '3.9'

services:
  mysql-admin-management-db:
    image: mysql:latest
    container_name: container_mysql-admin-management-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin-management-db
      MYSQL_USER: diallo
      MYSQL_PASSWORD: passer
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD


  phpmyadmin-admin-db:
    container_name: container_phpmyadmin-adminmgntdb
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8085:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-admin-management-db
      PMA_USER: diallo
      PMA_PASSWORD: passer
    depends_on:
      - mysql-admin-management-db
    restart: unless-stopped

  # configuration de keycloak
  keycloak:
    image: bitnami/keycloak:23.0.6
    container_name: auth_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080

volumes:
  mysql_data:
    driver: local