server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin-management-db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  application:
    name: spring-admin-management

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/admin-realm
          jwt-set-uri: http://localhost:8080/realms/admin-realm/protocol/openid-connect/certs

  info:
    application:
      name: admin-management
      version: '@project.version@'

logging:
  file:
    name: E:/cours/M2/JAVA/tp/admin-management/logs/logs.log